# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker

env:
  global:
    - CRATE_NAME=taskpaper

matrix:
  include:
    # Linux
    - env: TARGET=armv7-unknown-linux-gnueabihf
      rust: nightly
    - env: TARGET=i686-unknown-linux-musl
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-musl
      rust: nightly

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: "hRtZImTg4kxdpP4vGqEDzVwzBkwyW+TUexIeLXPhtZT4JfNbWArQR2VDURpyqJXKQ5kpq0qxS+wCPHw3bZTwGfm6+5rKLGv1FiM3hDR4y+tDQAn2F+e+YcdkGzJJ25fgY+Pg1QHVpPSsWd/DAMTQSm45L/4UXj8dgeudNd/BlmWbHfMmzkWbfOcPD2ll1CElid3DFt8AI1cFb43pGzB8+NqaJpY+IDsnqLRrHDiUehOx6CakDDHWp2MDpO8cr+QUx7C55qTQcxMecsie1Hz9nedl9/hZH2Wj+MNdoBeIBnTvvcQjQ+Y5G96BWFynA//ov8KOCYxMcS0UEQYrG13jOvXiijJS19IA7FnexeBr405dL19SIRNSf4w53/5ClJj1Z6hTdx35M5xtbj5UIiMaCJdgTh+2LNqRURnzPuRF33y8POikpjgJmUlq2xJ9kUd5eFzDuM3uWV9Dr3/EqljC3wQUf6OT5kPyDLa8lRlWFyxbnL9DY6E0GhQeSRIRm8XcfrZKMmJeQDK1zURecfXYulcMiBROyyunhTHyURcrTk7jYtmasRVmuSFnkjelVJEdS3+BBtrWpPrcIyfwBPh1QJ3jny/S8XlpJC/2Q3UeIAGbBaO8O3vE6mOgLGNQB40B6gCOO2xB9YrzN3RYrWxNsr+JGBB96u1y2qrpUlFFxfc="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = nightly
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
