[target.i686-unknown-linux-musl]
image = "sirver/i686-unknown-linux-musl-x11:latest"

[target.x86_64-unknown-linux-musl]
image = "sirver/x86_64-unknown-linux-musl-x11:latest"

[target.armv7-unknown-linux-gnueabihf]
image = "sirver/armv7-unknown-linux-gnueabihf-x11:latest"

